import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createChaseServer} from '../server/chase-server';
import {watchChase} from './chase-browser-helpers';
import {captureFrame} from './chase-capture';

// This fixture drives authoritative server state to rare moments. It verifies
// their delivery/rendering, not the balance or normal player path to those moments.
test('rare feedback reaches two independent clients and stays inside phone controls',async({browser})=>{
  test.setTimeout(75000);const evidence=process.env.DDG_FEEDBACK_EVIDENCE_DIR??'test-results/feedback';await mkdir(evidence,{recursive:true});
  const fixture=createChaseServer({clientDir:resolve('dist/client')});await new Promise<void>(r=>fixture.server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${(fixture.server.address() as {port:number}).port}`;
  const contexts=await Promise.all([{width:667,height:375},{width:1366,height:768}].map(viewport=>browser.newContext({viewport}))),pages=await Promise.all(contexts.map(c=>c.newPage())),states=pages.map(watchChase),probes:any[]=[];
  async function probe(page:Page){const cdp=await page.context().newCDPSession(page);let script='';cdp.on('Debugger.scriptParsed',s=>{if(/\/assets\/index-.*\.js$/.test(s.url))script=s.scriptId;});await cdp.send('Debugger.enable');
    await page.addInitScript(()=>{const samples:any[]=[];(window as any).__feedback=samples;(window as any).__sampleFeedback=(v:any)=>{if(!v.figures)return;const at=performance.now();samples.push({at,figures:[...v.figures].map(([id,f]:any)=>({id,role:f.role,tell:f.tell?.visible??false,stars:f.stars?.visible??false,slow:(f.slowUntil??0)>at,reveal:(f.revealUntil??0)>at,shield:f.shield?.visible??false,z:f.root.position.z,eyes:f.eyes?.visible??false,marker:f.marker.scale.x})),drops:v.dropped?.filter((d:any)=>d.mesh.visible).length??0,dropPool:v.dropped?.length??0,particles:v.effects?Array.from(v.effects.life).filter((n:any)=>n>0).length:0,lamp:v.lampHalo?.material.opacity,sky:v.scene.background.getHexString()});if(samples.length>600)samples.shift();};});
    return {cdp,getScript:()=>script};}
  try{
    for(const page of pages)probes.push(await probe(page));await pages[0].goto(url);await pages[0].getByRole('button',{name:'Play',exact:true}).click();await expect.poll(()=>states[0].snapshot?.code).toBeTruthy();await pages[1].goto(url);await pages[1].getByRole('textbox',{name:'Room code'}).fill(states[0].snapshot!.code);await pages[1].getByRole('button',{name:'Join friends'}).click();await expect.poll(()=>states.every(s=>s.snapshot?.multi?.stage==='playing'),{timeout:12000}).toBe(true);
    for(let i=0;i<2;i++){await expect(pages[i].locator('canvas')).toHaveAttribute('aria-busy','false');const {cdp,getScript}=probes[i];await expect.poll(getScript).toBeTruthy();const source=(await cdp.send('Debugger.getScriptSource',{scriptId:getScript()})).scriptSource,at=source.lastIndexOf('this.renderer.render(this.scene,this.camera)'),before=source.slice(0,at);expect(at).toBeGreaterThan(0);await cdp.send('Debugger.setBreakpoint',{location:{scriptId:getScript(),lineNumber:before.split('\n').length-1,columnNumber:at-before.lastIndexOf('\n')-1},condition:'(requestAnimationFrame(()=>window.__sampleFeedback(this)),false)'});}
    const room=fixture.rooms.get(states[0].snapshot!.code)!,sim=room.sim,kid=sim.entities.find(e=>e.id===states[0].id)!,goose=sim.entities.find(e=>e.id===states[1].id)!;
    for(const e of sim.entities){e.bot=false;e.held=false;e.vx=0;e.vz=0;e.safeUntil=sim.now+1000;e.frozenUntil=0;}kid.role='kid';kid.x=-4;kid.z=6;kid.frozenUntil=sim.now+1000;goose.role='goose';goose.x=0;goose.z=6;goose.lungeAt=-100;goose.immuneUntil=0;
    await expect(pages[0].locator('#role-card')).toBeHidden();await expect.poll(()=>states[0].snapshot!.entities.find(e=>e.id===kid.id)?.x).toBe(-4);
    const observed=async(page:Page,key:string,id=goose.id)=>page.evaluate(({key,id})=>(window as any).__feedback.some((s:any)=>s.figures.some((f:any)=>f.id===id&&f[key])),{key,id});
    // Keep the committed wind-up alive for120ms, exactly as the normal rule does.
    goose.lungeAt=sim.now;goose.lungeAngle=Math.PI/2;sim.event('windup',goose);await expect.poll(()=>observed(pages[0],'tell'),{timeout:3000,intervals:[25,50]}).toBe(true);
    sim.event('miss',goose);sim.event('near',goose,kid);await expect(pages[0].locator('#message')).toContainText('CLOSE! +50');await expect.poll(()=>observed(pages[0],'stars')).toBe(true);await expect.poll(()=>observed(pages[0],'slow',kid.id)).toBe(true);
    await captureFrame(pages[0],`${evidence}/near-667.png`);
    kid.battery=20;await expect(pages[0].locator('#action-state')).toContainText('LOW');await expect(pages[0].locator('#pickup-hint')).toBeVisible();await captureFrame(pages[0],`${evidence}/low-667.png`);
    kid.battery=5;await expect(pages[0].locator('#action-state')).toHaveText('EMPTY');kid.battery=20;sim.pickups[0]={x:kid.x,z:kid.z,readyAt:0};await expect.poll(()=>states[0].snapshot?.events.some(e=>e.type==='pickup'&&e.actor===kid.id)).toBe(true);await expect.poll(()=>states[0].snapshot?.entities.find(e=>e.id===kid.id)?.battery).toBeGreaterThan(60);
    // Lamp uses its real occupied countdown, with the fixture placing it at the kid.
    sim.lamps[0]={x:kid.x,z:kid.z,remaining:1.2,readyAt:0,active:false};await expect.poll(()=>states[0].snapshot?.lamps?.[0]?.active).toBe(true);await expect.poll(()=>pages[0].evaluate(()=>(window as any).__feedback.some((s:any)=>s.lamp<.2&&s.lamp>0))).toBe(true);await expect.poll(()=>states[0].snapshot?.lamps?.[0]?.active,{timeout:3000}).toBe(false);
    // Only one remaining kid triggers the actual last-kid rule/refill.
    for(const e of sim.entities)if(e.id!==kid.id){e.role='goose';e.safeUntil=sim.now+1000;}await expect.poll(()=>states[0].snapshot?.multi?.lastKid).toBe(kid.id);await expect(pages[1].locator('#threat')).toContainText('LAST KID');await expect.poll(()=>pages[0].evaluate(id=>(window as any).__feedback.some((s:any)=>s.figures.some((f:any)=>f.id===id&&f.marker>1.2)),kid.id)).toBe(true);
    sim.elapsed=65;room.multi!.deadline=Date.now()+9800;await expect(pages[0].locator('#recharge')).toBeVisible();await expect(pages[0].locator('#final-count')).toBeVisible();await expect(pages[1].locator('#final-count')).toBeVisible();
    for(let i=0;i<2;i++){const b=await pages[i].locator('#recharge').boundingBox();if(i===0){expect(b).toBeTruthy();expect(b!.x+b!.width).toBeLessThanOrEqual(667);}await captureFrame(pages[i],`${evidence}/finale-${i===0?667:1366}.png`);}
    await expect.poll(()=>states.every(s=>s.snapshot?.phase==='results'),{timeout:12000}).toBe(true);await expect(pages[0].locator('#results')).toBeVisible();await expect(pages[1].locator('#results')).toBeVisible();expect(states[0].snapshot!.events.some(e=>e.type==='dawn')).toBe(true);await expect(pages[0].locator('#result-title')).toContainText('Dawn');const firstScoreText=await pages[0].locator('#scores').textContent(),finalScoreText=[...states[0].snapshot!.multi!.scores].sort((a,b)=>b.total-a.total).map(p=>`${p.name}: ${Math.floor(p.total)}`).join(' · ');await expect(pages[0].locator('#scores')).toHaveText(finalScoreText);expect(firstScoreText).not.toBe(finalScoreText);
    await expect.poll(()=>pages[0].evaluate(id=>{const samples=(window as any).__feedback;const z=samples.flatMap((s:any)=>s.figures.filter((f:any)=>f.id===id&&!f.eyes).map((f:any)=>f.z));return z.length?Math.max(...z)-Math.min(...z):0;},goose.id)).toBeGreaterThan(.5);
    for(let i=0;i<2;i++){await captureFrame(pages[i],`${evidence}/dawn-${i===0?667:1366}.png`);expect(await pages[i].evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.documentElement.scrollHeight===innerHeight)).toBe(true);}
    const report={fixtureDriven:true,normalFullRoundsCoveredBy:'chase-multi.spec.ts',windup:true,missStars:true,nearSlowAnimation:true,lowAndEmpty:true,realPickup:true,lampExpiry:true,lastKidRefill:true,finalCountdownBothSessions:true,dawnBothSessions:true,ordinaryGooseWalkOff:true,scoreCountUp:{first:firstScoreText,final:finalScoreText},errors:states.flatMap(s=>s.errors)};expect(report.errors).toEqual([]);await writeFile(`${evidence}/feedback.json`,JSON.stringify(report,null,2));
  }finally{await Promise.all(contexts.map(c=>c.close()));await fixture.close();}
});
