import {test,expect,type Page} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
import {resolve} from 'node:path';
import {pickUpFlashlight,walkAxis} from './round-regression-helpers';
const address='http://127.0.0.1:5182';let child:ChildProcess;
test.beforeAll(async()=>{
 const source=`import {createGameServer} from ${JSON.stringify(new URL('../dist/server/server/index.js',import.meta.url).href)};const game=createGameServer({clientDir:${JSON.stringify(resolve('dist/client'))},roundDurations:{blackoutMs:100,hidingMs:15000,seekingMs:16000,revealMs:1500,nextRoundMs:7000}});game.server.listen(5182,'127.0.0.1');`;
 child=spawn(process.execPath,['--input-type=module','-e',source],{stdio:'pipe'});let failure='';child.stderr!.on('data',data=>failure+=data);
 await expect.poll(async()=>{if(child.exitCode!==null)throw new Error(failure);try{return(await fetch(address)).status;}catch{return 0;}},{timeout:15000}).toBe(200);
});
test.afterAll(()=>child?.kill());
async function create(p:Page,name='Alex'){await p.goto(address);await p.getByLabel('Your name').fill(name);await p.getByRole('button',{name:'Create a night',exact:true}).click();return p.getByTestId('room-code').innerText();}
async function join(p:Page,code:string){await p.goto(`${address}/?room=${code}`);await p.getByLabel('Your name').fill('Sam');await p.getByRole('button',{name:'Join',exact:true}).click();}
async function ready(p:Page){await p.locator('canvas[data-ready="true"]').waitFor();}
async function fit(p:Page){expect(await p.evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.documentElement.scrollHeight===innerHeight)).toBe(true);const bad=await p.locator('button:not([hidden]),#role-card,#orientation-hint').evaluateAll(elements=>elements.filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').filter(e=>{const r=e.getBoundingClientRect();const phrase=Boolean(e.closest('#radio-phrases'));return (!phrase&&(r.x<-.5||r.right>innerWidth+.5))||r.y<-.5||r.bottom>innerHeight+.5||(e.tagName==='BUTTON'&&r.height<44);}).map(e=>({text:e.textContent,rect:e.getBoundingClientRect().toJSON()})));expect(bad).toEqual([]);}

test('title describes the game; portrait hint belongs to play; real Chromium fullscreen enters and exits',async({browser})=>{
 test.setTimeout(40000);const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});const p=await context.newPage();try{
  await p.goto(address);await expect(p.locator('#title-description')).toHaveText('Dark hide-and-seek. 1 to 6 players.');await expect(p.locator('#orientation-hint')).toHaveCount(0);await p.setViewportSize({width:667,height:375});expect(await p.locator('#title-description').evaluate(e=>{const r=e.getBoundingClientRect(),style=getComputedStyle(e);return r.height<=parseFloat(style.fontSize)*1.8&&r.x>=0&&r.right<=innerWidth;})).toBe(true);await p.screenshot({path:'../design/finishing-title-phone.png'});await p.setViewportSize({width:390,height:844});
  await p.getByLabel('Your name').fill('Alex');await p.getByRole('button',{name:'Create a night',exact:true}).click();await expect(p.locator('#orientation-hint')).toHaveCount(0);await p.getByRole('button',{name:'Start the night',exact:true}).click();await ready(p);await expect(p.locator('#orientation-hint')).toBeVisible();await p.screenshot({path:'../design/finishing-portrait-play-phone.png'});
  await p.setViewportSize({width:667,height:375});await expect(p.locator('#orientation-hint')).toBeHidden();await expect(p.locator('#fullscreen')).toBeVisible();expect(await p.evaluate(()=>document.fullscreenEnabled)).toBe(true);await p.locator('#fullscreen').click();await expect.poll(()=>p.evaluate(()=>Boolean(document.fullscreenElement))).toBe(true);await p.locator('#fullscreen').click();await expect.poll(()=>p.evaluate(()=>document.fullscreenElement===null)).toBe(true);await fit(p);await p.screenshot({path:'../design/finishing-fullscreen-phone.png'});
 }finally{await context.close();}
});

test('unsupported fullscreen gives a dismissible install tip remembered on this device',async({browser})=>{
 test.setTimeout(30000);const context=await browser.newContext({viewport:{width:667,height:375},hasTouch:true});await context.addInitScript(()=>{Object.defineProperty(Document.prototype,'fullscreenEnabled',{configurable:true,get:()=>false});Object.defineProperty(HTMLElement.prototype,'requestFullscreen',{configurable:true,value:undefined});});const p=await context.newPage();try{
  await create(p);await p.getByRole('button',{name:'Start the night',exact:true}).click();await ready(p);await expect(p.locator('#fullscreen')).toHaveCount(0);await expect(p.locator('#install-tip')).toBeVisible();await fit(p);await p.screenshot({path:'../design/finishing-install-tip-phone.png'});await p.locator('#dismiss-install-tip').click();await expect(p.locator('#install-tip')).toBeHidden();await p.reload();await ready(p);await expect(p.locator('#install-tip')).toHaveCount(0);await expect(p.locator('#fullscreen')).toHaveCount(0);
 }finally{await context.close();}
});

test('hider and seeker role cards fade without replaying on snapshots; first contextual action draws attention',async({browser})=>{
 test.setTimeout(40000);const phone=await browser.newContext({viewport:{width:667,height:375},hasTouch:true}),laptop=await browser.newContext({viewport:{width:1366,height:768}});const a=await laptop.newPage(),b=await phone.newPage();try{
  const code=await create(a);await join(b,code);await a.getByRole('button',{name:'Start the night',exact:true}).click();await Promise.all([ready(a),ready(b)]);await expect(a.locator('#role-card')).toContainText('You are hiding.');await expect(b.locator('#role-card')).toContainText('Find the capsule.');await fit(a);await fit(b);await a.screenshot({path:'../design/finishing-hider-role-laptop.png'});await b.screenshot({path:'../design/finishing-seeker-role-phone.png'});
  const cards=[await a.locator('#role-card').elementHandle(),await b.locator('#role-card').elementHandle()];await Promise.all([expect(a.locator('#role-card')).toBeHidden({timeout:7000}),expect(b.locator('#role-card')).toBeHidden({timeout:7000})]);await a.keyboard.down('d');await a.waitForTimeout(250);await a.keyboard.up('d');await a.waitForTimeout(1000);for(const[p,card]of[[a,cards[0]],[b,cards[1]]]as const){expect(await card!.evaluate(e=>e===document.querySelector('#role-card'))).toBe(true);await expect(p.locator('#role-card')).toBeHidden();}
  await walkAxis(b,'x',0);await walkAxis(b,'z',-1.1);await expect(b.locator('#round-action')).toContainText('Pick up');await expect(b.locator('#round-action')).toHaveClass(/action-attention/);await b.screenshot({path:'../design/finishing-action-attention-phone.png'});await b.locator('#round-action').click();await expect(b.locator('#round-action')).toBeHidden();await expect(a.locator('canvas')).toHaveAttribute('data-round-phase','seeking',{timeout:17000});await a.reload();await ready(a);await expect(a.locator('#role-card')).toContainText('Leave misleading trails');await expect(a.locator('#role-card')).not.toContainText('Bury the capsule');await a.screenshot({path:'../design/finishing-hider-seeking-refresh-laptop.png'});
 }finally{await phone.close();await laptop.close();}
});

test('solo card explains seeking and the phone radio is a persistent top dock leaving controls reachable',async({browser})=>{
 test.setTimeout(35000);const context=await browser.newContext({viewport:{width:667,height:375},hasTouch:true});const p=await context.newPage();try{
  await create(p,'Robin');await p.getByRole('button',{name:'Start the night',exact:true}).click();await ready(p);await expect(p.locator('#role-card')).toContainText('Find the capsule.');await p.screenshot({path:'../design/finishing-solo-role-phone.png'});await pickUpFlashlight(p);await p.locator('#radio-toggle').click();await expect(p.locator('#radio-panel')).toBeVisible();const box=await p.locator('#radio-panel').boundingBox();expect(box!.y).toBeGreaterThanOrEqual(0);expect(box!.y+box!.height).toBeLessThanOrEqual(187.5);await fit(p);const last=p.locator('#radio-phrases button').last(),phrase=(await last.innerText()).trim();await last.scrollIntoViewIfNeeded();const phraseBox=await last.boundingBox();expect(phraseBox!.x).toBeGreaterThanOrEqual(0);expect(phraseBox!.x+phraseBox!.width).toBeLessThanOrEqual(667);await last.click();await expect(p.locator('#radio-history')).toContainText(phrase);await expect(p.locator('#role-card')).toBeHidden({timeout:7000});
   for(const [direction,key] of [['north','w'],['east','d'],['south','s'],['west','a']]){await p.keyboard.down(key);await p.waitForTimeout(60);await p.keyboard.up(key);await p.waitForTimeout(1000);const geometry=await p.evaluate(()=>{const canvas=document.querySelector<HTMLCanvasElement>('canvas')!,raw=JSON.parse(canvas.dataset.characterBounds??'null'),cr=canvas.getBoundingClientRect(),panel=document.querySelector('#radio-panel')!.getBoundingClientRect();const body=raw?{x:raw.x+cr.x,y:raw.y+cr.y,width:raw.width,height:raw.height}:null;return{body,panel:{x:panel.x,y:panel.y,width:panel.width,height:panel.height},overlap:body?body.x<panel.right&&body.x+body.width>panel.x&&body.y<panel.bottom&&body.y+body.height>panel.y:true};});console.log(`Radio dock ${direction}: ${JSON.stringify(geometry)}`);expect(geometry.overlap).toBe(false);await p.screenshot({path:`../design/finishing-radio-${direction}-phone.png`});}
   await p.locator('#radio-input').fill('Keep this draft');await p.locator('#radio-input').focus();await p.evaluate(()=>{(window as any).finishingNodes=['#radio-panel','#radio-input','#move-stick','#round-action'].map(s=>document.querySelector(s));});await p.waitForTimeout(1000);await expect(p.locator('#radio-input')).toBeFocused();await expect(p.locator('#radio-input')).toHaveValue('Keep this draft');expect(await p.evaluate(()=>['#radio-panel','#radio-input','#move-stick','#round-action'].every((s,i)=>document.querySelector(s)===(window as any).finishingNodes[i]))).toBe(true);await p.screenshot({path:'../design/finishing-radio-dock-phone.png'});await p.setViewportSize({width:667,height:235});await fit(p);await expect(p.locator('#radio-input')).toBeFocused();await expect(p.locator('#radio-input')).toHaveValue('Keep this draft');await p.screenshot({path:'../design/finishing-radio-keyboard-height-phone.png'});
 }finally{await context.close();}
});
