import {test,expect,type Page} from '@playwright/test';
import {spawn,type ChildProcess} from 'node:child_process';
import {resolve} from 'node:path';
import type {RoomSnapshot,ServerMessage} from '../shared/protocol';
import {getRadioPhrases,RADIO_HISTORY_LIMIT} from '../shared/radio';
import {localPose,pickUpFlashlight} from './round-regression-helpers';
const address='http://127.0.0.1:5179';let child:ChildProcess;
test.beforeAll(async()=>{
 const source=`import {createGameServer} from ${JSON.stringify(new URL('../dist/server/server/index.js',import.meta.url).href)}; const game=createGameServer({clientDir:${JSON.stringify(resolve('dist/client'))},roundDurations:{blackoutMs:100,hidingMs:6000,seekingMs:12000,revealMs:1200,nextRoundMs:7000},clueIntervalMs:2000,clueChoiceMs:250}); game.server.listen(5179,'127.0.0.1');`;
 child=spawn(process.execPath,['--input-type=module','-e',source],{stdio:'pipe'});let failure='';child.stderr!.on('data',data=>failure+=data);
 await expect.poll(async()=>{if(child.exitCode!==null)throw new Error(failure);try{return(await fetch(address)).status;}catch{return 0;}},{timeout:15000}).toBe(200);
});
test.afterAll(()=>child?.kill());
function observe(page:Page){const frames:any[]=[],sent:any[]=[];page.on('websocket',ws=>{ws.on('framereceived',f=>{try{frames.push(JSON.parse(String(f.payload)));}catch{}});ws.on('framesent',f=>{try{sent.push(JSON.parse(String(f.payload)));}catch{}});});return{frames,sent,room:()=>frames.flatMap(m=>m.room?[m.room as RoomSnapshot]:[]).at(-1)!};}
async function create(p:Page){await p.goto(address);await p.getByLabel('Your name').fill('Alex');await p.getByRole('button',{name:'Create a night',exact:true}).click();return p.getByTestId('room-code').innerText();}
async function join(p:Page,code:string,name='Sam'){await p.goto(`${address}/?room=${code}`);await p.getByLabel('Your name').fill(name);await p.getByRole('button',{name:'Join',exact:true}).click();}
async function radio(p:Page){if(!await p.locator('#radio-panel').isVisible())await p.locator('#radio-toggle').click();await expect(p.locator('#radio-panel')).toBeVisible();}
async function typed(p:Page,text:string){await radio(p);await p.locator('#radio-input').fill(text);await p.locator('#radio-send').click();}
async function quick(p:Page){await radio(p);const first=p.locator('#radio-phrases button').first(),text=(await first.innerText()).trim();await first.click();return text;}
async function screen(p:Page){expect(await p.evaluate(()=>document.documentElement.scrollWidth===innerWidth&&document.documentElement.scrollHeight===innerHeight)).toBe(true);const bad=await p.locator('#radio-panel').evaluate(panel=>[...panel.querySelectorAll('input,button')].filter(e=>e.getClientRects().length).filter(e=>{const r=e.getBoundingClientRect();return r.x<0||r.y<0||r.right>innerWidth+.5||r.bottom>innerHeight+.5||r.height<44||parseFloat(getComputedStyle(e).fontSize)<16;}).map(e=>({text:e.textContent,rect:e.getBoundingClientRect().toJSON()})));expect(bad).toEqual([]);const overlaps=await p.evaluate(()=>{const visible=(selector:string)=>{const e=document.querySelector<HTMLElement>(selector);return e&&e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'?e.getBoundingClientRect():null;};const panel=visible('#radio-panel'),toggle=visible('#radio-toggle');const results:string[]=[];for(const selector of ['#move-stick','#round-action','.round-hud']){const box=visible(selector);if(!box)continue;for(const [name,r] of [['panel',panel],['toggle',toggle]] as const)if(r&&box.x<r.right&&box.right>r.x&&box.y<r.bottom&&box.bottom>r.y)results.push(`${name}/${selector}`);}const code=visible('#street-code'),hud=visible('.round-hud');if(code&&hud&&code.x<hud.right&&code.right>hud.x&&code.y<hud.bottom&&code.bottom>hud.y)results.push('room code/countdown');return results;});expect(overlaps).toEqual([]);}
async function phraseIDs(p:Page){return p.locator('#radio-phrases button').evaluateAll(buttons=>buttons.map(b=>(b as HTMLElement).dataset.phraseId));}

test('two independent sessions exchange contextual radio; draft, focus, movement and phone keyboard layout stay intact',async({browser})=>{
 test.setTimeout(90000);const phone=await browser.newContext({viewport:{width:667,height:375},hasTouch:true}),laptop=await browser.newContext({viewport:{width:1366,height:768}});const a=await laptop.newPage(),b=await phone.newPage(),ao=observe(a),bo=observe(b);const errors:string[]=[];for(const p of[a,b])p.on('pageerror',e=>errors.push(e.message));
 try{
  const code=await create(a);await join(b,code);await a.getByRole('button',{name:'Start the night',exact:true}).click();for(const p of[a,b])await p.locator('canvas[data-ready="true"]').waitFor();
  await radio(a);await radio(b);await expect.poll(()=>ao.room().round!.phase).toBe('hiding');expect(await phraseIDs(a)).toEqual(getRadioPhrases(ao.room(),ao.room().hostId).map(p=>p.id));expect(await phraseIDs(b)).toContain('prep-light');
  const sentAt=Date.now(),hiderText=await quick(a);await expect(b.locator('#radio-history')).toContainText(hiderText);const arrival=Date.now()-sentAt;console.log(`Radio UI arrival: ${arrival} ms`);expect(arrival).toBeLessThan(500);await typed(b,'I have the light.');await expect(a.locator('#radio-history')).toContainText('I have the light.');
  await b.locator('#radio-toggle').click();await pickUpFlashlight(b);await expect(b.locator('canvas')).toHaveAttribute('data-round-phase','seeking',{timeout:15000});await radio(b);
  await expect.poll(()=>phraseIDs(b)).toContain('footprints');await expect.poll(()=>phraseIDs(a)).toContain('catch');
  const before=await localPose(b),actions=bo.sent.filter(m=>['bury','pickup','search_begin','search_complete'].includes(m.type)).length;
  await b.locator('#radio-input').fill('Unsaved draft ');await b.locator('#radio-input').focus();await b.keyboard.type('wasdEr',{delay:65});await b.waitForTimeout(250);await expect(b.locator('#radio-input')).toBeFocused();await expect(b.locator('#radio-input')).toHaveValue('Unsaved draft wasdEr');expect(Math.hypot((await localPose(b)).x-before.x,(await localPose(b)).z-before.z)).toBeLessThan(.12);expect(bo.sent.filter(m=>['bury','pickup','search_begin','search_complete'].includes(m.type)).length).toBe(actions);await b.keyboard.press('Escape');await expect(b.locator('#radio-panel')).toBeHidden();await radio(b);await expect(b.locator('#radio-input')).toHaveValue('Unsaved draft wasdEr');await b.locator('#radio-input').focus();
  await b.evaluate(()=>{(window as any).radioNodes=['#radio-panel','#radio-input','#radio-history','#radio-send'].map(s=>document.querySelector(s));});
  await typed(a,'Meet by the sidewalk.');await expect(b.locator('#radio-history')).toContainText('Meet by the sidewalk.');await expect(b.locator('#radio-input')).toBeFocused();await expect(b.locator('#radio-input')).toHaveValue('Unsaved draft wasdEr');expect(await b.evaluate(()=>['#radio-panel','#radio-input','#radio-history','#radio-send'].every((s,i)=>document.querySelector(s)===(window as any).radioNodes[i]))).toBe(true);
  const waiting=await phone.newPage();await join(waiting,code,'Jess');await waiting.locator('canvas[data-ready="true"]').waitFor();await expect(waiting.locator('canvas')).toHaveAttribute('data-role','waiting');await radio(waiting);expect(await phraseIDs(waiting)).toContain('waiting-next');await quick(waiting);await expect(b.locator('#radio-history')).toContainText('Ready when you are.');await expect(b.locator('#radio-input')).toBeFocused();await expect(b.locator('#radio-input')).toHaveValue('Unsaved draft wasdEr');
  await expect.poll(()=>b.locator('#radio-history li[data-kind="clue"]:not([hidden])').count(),{timeout:7000}).toBeGreaterThan(0);await screen(b);await b.screenshot({path:'../design/step7-radio-phone.png'});
  await b.setViewportSize({width:667,height:235});await screen(b);await expect(b.locator('#radio-input')).toBeFocused();await b.screenshot({path:'../design/step7-radio-keyboard-height-phone.png'});await b.setViewportSize({width:667,height:375});
  await b.locator('#radio-input').evaluate(input=>(input as HTMLInputElement).blur());const draft=await b.locator('#radio-input').inputValue();const walk=await localPose(b);await b.keyboard.down('d');await b.waitForTimeout(350);await b.keyboard.up('d');expect((await localPose(b)).x).toBeGreaterThan(walk.x+.7);await expect(b.locator('#radio-input')).toHaveValue(draft);
  await b.keyboard.press('r');await expect(b.locator('#radio-panel')).toBeHidden();await b.keyboard.press('r');await expect(b.locator('#radio-panel')).toBeVisible();expect(errors).toEqual([]);
 }finally{await phone.close();await laptop.close();}
});

test('radio flood is friendly and cannot stop movement; bounded history restores and phrases work through reveal and final',async({browser})=>{
 test.setTimeout(155000);const phone=await browser.newContext({viewport:{width:667,height:375},hasTouch:true}),laptop=await browser.newContext({viewport:{width:1366,height:768}});const a=await laptop.newPage(),b=await phone.newPage(),ao=observe(a),bo=observe(b);
 try{
  const code=await create(a);await join(b,code);await a.getByRole('button',{name:'Start the night',exact:true}).click();for(const p of[a,b])await p.locator('canvas[data-ready="true"]').waitFor();await radio(a);await radio(b);
  // Bypass only the UI throttle using the actual live connection. Movement keeps its own allowance.
  const otherBefore=await localPose(a),otherId=ao.room().hostId,floodAt=Date.now();await a.keyboard.down('d');
  await b.evaluate(()=>{const original=WebSocket.prototype.send;WebSocket.prototype.send=function(data){original.call(this,data);if(typeof data==='string'&&JSON.parse(data).type==='move'){WebSocket.prototype.send=original;for(let i=0;i<20;i++)original.call(this,JSON.stringify({id:`radio-flood-${i}`,type:'radio',text:`Flood test ${i}`}));}};});
  await b.waitForTimeout(350);await a.keyboard.up('d');expect((await localPose(a)).x).toBeGreaterThan(otherBefore.x+.7);await expect.poll(()=>ao.room().players.find(p=>p.id===otherId)?.x??otherBefore.x,{timeout:500}).toBeGreaterThan(otherBefore.x+.7);const movementAck=Date.now()-floodAt;expect(movementAck).toBeLessThan(500);const fps=Number(await a.locator('canvas').getAttribute('data-fps'));if(fps>0)expect(fps).toBeGreaterThanOrEqual(30);console.log(`Other player moves during radio flood: accepted after ${movementAck} ms; ${fps||'sampling'} FPS`);
  await expect.poll(()=>bo.frames.some(m=>m.type==='result'&&!m.ok&&m.error?.code==='radio_rate_limited')).toBe(true);await b.waitForTimeout(180);await quick(b);await expect(b.locator('#radio-note')).toContainText(/settle|seconds|wait/i);await b.locator('#radio-input').evaluate(input=>(input as HTMLInputElement).blur());const start=await localPose(b);await b.keyboard.down('d');await b.waitForTimeout(350);await b.keyboard.up('d');expect((await localPose(b)).x).toBeGreaterThan(start.x+.7);expect(bo.frames.some(m=>m.type==='seat_replaced')).toBe(false);
  await b.locator('#radio-input').fill('x'.repeat(90));await b.locator('#radio-send').click();await expect(b.locator('#radio-note')).toContainText('80');await b.locator('#radio-input').fill('');
  for(let n=1;n<=4;n++){
   await expect.poll(()=>ao.room().match!.roundNumber,{timeout:12000}).toBe(n);await expect(a.locator('canvas')).toHaveAttribute('data-round-phase','seeking',{timeout:18000});
   if(n===1){await typed(a,'w'.repeat(80));await expect(b.locator('#radio-history')).toContainText('w'.repeat(80));}await typed(a,`Round ${n}: <b>plain text</b>`);await expect(b.locator('#radio-history')).toContainText(`Round ${n}: <b>plain text</b>`);expect(await b.locator('#radio-history b').count()).toBe(0);
   await b.waitForTimeout(5200);await quick(a);await quick(b);await typed(a,`Keep searching ${n}.`);await typed(b,`Copy that ${n}.`);
   await expect(a.locator('#match-panel')).toBeVisible({timeout:12000});await radio(a);await radio(b);expect(await phraseIDs(a)).toContain(n===4?'again':'next');await screen(b);
   await quick(a);await a.locator('#radio-toggle').click();await b.locator('#radio-toggle').click();await typed(a,`Round ${n} finished. See you by the windows.`);await a.locator('#radio-toggle').click();
   for(const p of[a,b]){await expect(p.locator('#clue-transmission')).toBeVisible();await expect(p.locator('#clue-transmission')).toContainText(`Round ${n} finished.`);expect(await p.evaluate(()=>{const caption=document.querySelector('#clue-transmission')!.getBoundingClientRect(),panel=document.querySelector('#match-panel')!.getBoundingClientRect();return caption.x>=panel.x&&caption.right<=panel.right&&caption.y>=panel.y&&caption.bottom<=panel.bottom;})).toBe(true);}
   if(n===1)await b.screenshot({path:'../design/step7-radio-scoreboard-phone.png'});if(n===4)await b.screenshot({path:'../design/step7-radio-final-phone.png'});
   if(n<4){await expect(a.locator('#next-round')).toBeEnabled();await a.locator('#next-round').click();await radio(a);await radio(b);}
  }
  expect(ao.room().match!.phase).toBe('finished');await expect.poll(()=>bo.room().radio!.length).toBe(RADIO_HISTORY_LIMIT);await expect(b.locator('#radio-history li:not([hidden])')).toHaveCount(RADIO_HISTORY_LIMIT);const history=bo.room().radio!;expect(history.some(m=>m.kind==='clue'&&['Alex','Sam'].includes(m.senderName))).toBe(true);await b.reload();await b.locator('canvas[data-ready="true"]').waitFor();await radio(b);expect(bo.room().radio).toEqual(history);await expect(b.locator('#radio-history li:not([hidden])')).toHaveCount(RADIO_HISTORY_LIMIT);await quick(b);await expect(a.locator('#radio-history')).toContainText('One more night?');await screen(b);await b.locator('#radio-toggle').click();const previous=bo.room().match!.id;await b.locator('#play-again').click();await expect.poll(()=>bo.room().match!.id).not.toBe(previous);expect(bo.room().radio).toEqual([]);await radio(b);await expect(b.locator('#radio-history li:not([hidden])')).toHaveCount(0);
 }finally{await phone.close();await laptop.close();}
});
